### ISSUE TITLE
Update in source mode not saved

### ISSUE THREAD

**Issue by BTW-Kevin** [sonata-project/SonataFormatterBundle#225]
Hello,

I have search in opened issues and I havn't found my problem. When I wrote something in sources mode, my modification are not saved. When I wrote something in the other mode my modification are saved.

Thanks for your help. (and sorry for my english level ...)

**Comment by pix-art** [comment]
CKEditor has to be upgraded to 4.4+

https://dev.ckeditor.com/ticket/12031

**Comment by Aylarius** [comment]
Hi! 
I'm having a similar issue. With Sonata Page, on the Page Composer only, when I select rich text and then I update the content in the source mode of the CKEditor, the content is not saved and is not even sent in the request (it's the old data that is sent). However if I update the block on it's own editing page, it works out perfectly.
I tried different versions of ckeditor, ivory and formatter but I'm quite stuck here. 
Do you have any idea ?

Thanks in advance

**Comment by pix-art** [comment]
@Aylarius the way CKE works is by generating an iframe with the behavior of CKE, and on some event you save that content to a hidden input field. So what is happening for you is the event to save the content is not triggered. What helped for me was upgrading CKE to 4.4 as i subscribed above. Or you could do a manual fetch of the data and save it to your input field when you submit. But that requires a lot of hassle. 

Hope this kind of sets you in the right direction. 

Goodluck! 
Joeri

**Comment by Aylarius** [comment]
@pix-art Thanks for your reply! I was wondering if you can tell me how you proceeded to update CKE? Do you mean you've changed the files directly in the bundle? 
I understood there is one version of CKE in the ivoryckeditor bundle and another in the formatter bundle, but I can't figure out which one is used. I tried using the latest stable version of CKE (4.6) and added it in the config of the ivoryckeditor bundle but it did not work out.

**Comment by pix-art** [comment]
We removed the JS include in admin.yml as shown below:

```
sonata_admin:
    assets:
        javascripts:
            #Comment out the real CKE from sonata
            #- bundles/sonataformatter/vendor/ckeditor/ckeditor.js
            #We use our own CKE untill formater bundle upgrades to new version
            - js/vendor/ckeditor/ckeditor.js
```
