### ISSUE TITLE
Limit file size

### ISSUE THREAD

**Issue by jdeveloper** [sonata-project/SonataFormatterBundle#401]
I try to integrate sonata media with sonata formatter and all works great but I have two questios.

1. Can I limit filesize?
2. Why does it do not run validation of MIME Type?

My sonata formatter config:

```
sonata_formatter:
    default_formatter: richhtml
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions

    ckeditor:
        templates:
            browser: 'SonataFormatterBundle:Ckeditor:browser.html.twig'
            upload: 'SonataFormatterBundle:Ckeditor:upload.html.twig'
```

And my sonata media config: 

```
sonata_media:
  class:
    media: MediaBundle\Entity\Media
    gallery: MediaBundle\Entity\Gallery
    gallery_has_media: MediaBundle\Entity\GalleryHasMedia
  default_context: default
  db_driver: doctrine_orm
  contexts:
    default:
      download:
        strategy: sonata.media.security.public_strategy
      providers:
        - sonata.media.provider.image

      formats:
        small: { width: 100 , quality: 70}

  cdn:
    server:
      path: /uploads/media

  providers:
    image:
      filesystem: sonata.media.filesystem.local

  filesystem:
    local:
      directory:  %kernel.root_dir%/../web/uploads/media
      create:     false
```
