### ISSUE TITLE
Add custom parser

### ISSUE THREAD

**Issue by Filoz** [sonata-project/SonataFormatterBundle#68]
Hi,
I'm trying to add a custom parser for the bbcode. 
I created the formatter test: 
```
<?php
namespace Equiweb\CommonBundle\Formatter;

use Sonata\FormatterBundle\Formatter\BaseFormatter;

class BbcodeFormatter extends BaseFormatter
{
    /**
     * @param $text
     * @return string
     */
    public function transform($text)
    {
        return $text . 'test';
    }
}
```
I added the service 
```
  equiweb.formatter.bbcode:
    class : Equiweb\CommonBundle\Formatter\BbcodeFormatter
    tags : 
      - {name : sonata.text.formatter} 
```
and finally 
```
#config.yml
sonata_formatter:
    formatters:
#...
        bbcode:
            service: equiweb.formatter.bbcode
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig
```
The problem is that the service is not found: 
```
The service definition "equiweb.formatter.bbcode" does not exist.
```

If I edit the file formatter.xml within SonataFormatterBundle adding the definition of the service, then it works. 
```    
#formatter.xml
    
        <service id="sonata.formatter.text.bbcode" class="Equiweb\Common\CommonBundle\Formatter\BbcodeFormatter">
            <tag name="sonata.text.formatter"/>

        </service>
```

How can I solve?

thankyou!
