### ISSUE TITLE
is dependent on paid ckeditor, which is no anymore secure

### ISSUE THREAD

**Issue by mesiarm** [sonata-project/SonataFormatterBundle#798]
https://forum.xwiki.org/t/cke-editor-warning-4-22-1-version-not-secure/14020

**Comment by mesiarm** [comment]
Temporary workaround https://github.com/django-ckeditor/django-ckeditor/issues/761

**Comment by haivala** [comment]
just set:
```
fos_ck_editor:
  configs:
    default:
      versionCheck: false
```
